### ISSUE TITLE
Why GPL?

### ISSUE THREAD

**Issue by jayvdb** [alfiedotwtf/cwd#1]
GPL isnt very good for libraries.
Would you might switching to LGPL https://en.wikipedia.org/wiki/GNU_Lesser_General_Public_License , which is designed for libraries.

**Comment by alfiedotwtf** [comment]
Personally, having worked with proprietary black-boxed libraries that I've had to suffer to use, I've always liked the idea of virility of the GPL and the security blanket it affords you to always be able to the source.

However, you're right - companies don't like GPL because it taints their own software and so will avoid. In this respect, there doesn't seem to be any advantage of dual licensing or going to a weaker license vs just releasing something as Public Domain (which I have thought of doing before).

Just a thought, did you reject to use my library because the license would infect your binary? If so, that's probably more than enough for me to Public Domain something so that you're free to do what you want - because IANAL 😅

**Comment by jayvdb** [comment]
Yes, I cant use it in the context I wanted to because of the license.

fwiw, I also cant use "Public Domain" because that isnt a thing in the https://spdx.org/licenses/ , which is the list which tools like `cargo-deny` use, and my company uses `cargo-deny` to check licenses of all dependencies.

**Comment by alfiedotwtf** [comment]
Ok no problem...

With that list on the link, what's your requirement i.e a "Y" in both the "FSF Free/Libre?" and OSI Approved?" column etc? Let me know, I'll go through the list, and update the library (and hopefully all my crates) over the weekend.

**Comment by jayvdb** [comment]
either "FSF Free/Libre?" or "OSI Approved" is fine, but OSI Approved is easier, but the main criteria is whether it is non-viral, as viral licenses are approved by both.

**Comment by alfiedotwtf** [comment]
Ok no problem. I'll try to get it done by Monday morning. If not, please ping me in case I forget.

**Comment by alfiedotwtf** [comment]
Cool... having a look, it seems that 0BSD fits within what I'm after. I've pushed a new version.

Let me know if that version still fails your deny rules, but from reading a few things, I'm thinking it shouldn't 🤞

**Comment by jayvdb** [comment]
Perfect. Thank you.
